### ISSUE TITLE
無法查詢地號

### ISSUE THREAD

**Issue by chiahuaw** [g0v/posland#7]
您好，發現無法使用查詢地號功能，使用下列的範例連結也是一樣回傳404。
http://posland.g0v.io/?address=臺中市北區水源段282之5

**Comment by philipz** [comment]
查地號是用 landno
亦可將 posland 服務執行在自己電腦上，只要裝上 docker ，然後
`docker run -d -p 80:9192 philipz/posland`
就可以在自己電腦上面查地號。
http://localhost/?landno=臺中市北區水源段282之5

**Comment by jimyhuang** [comment]
之前offine，現在應該恢復了。也可像是 philipz 說的直接跑 philipz 的版本
http://posland.g0v.io/
